# EasyMissions default mission config
#
# This file is where you define templates that other missions fall back to if they are missing specific fields.
# For example, if a mission doesn't specify 'lore', it uses the lore defined here.
#
# You can define your own defaults, select a default for a mission by setting 'default' field to the top level key of your default.
#
# TAGS:
# [REWARDS!] -> Put this in a mission's reward list to include the default rewards defined below.
# [LORE!]    -> Put this in 'completed_lore' to automatically copy the normal 'lore', strike it through, and insert it there.
# [NAME]     -> Can be used in 'completed_name' to include the original mission name.

# The top level key of your default, must be unique
default:

  # The display name of the mission item
  # A list of placeholders can be found at https://github.com/Stevv63/EasyMissions/wiki/Config-%7C-Placeholders
  name: "<gradient:#FFAA00:#FFE500><shadow:#000000:1><b><type_cap> Mission</b></shadow></gradient>"

  # The display name when completed
  completed_name: "<green><bold>✔ COMPLETED</bold></green>"

  # The lore of the mission item
  lore:
    - "<!i><shadow:#000000:1><white>Complete the mission to earn a</shadow>"
    - "<gradient:#ffaa00:#ffe100><shadow:#000000:1>reward</gradient><white>."
    - ""
    - "<color:#FFFC00><shadow:#000000:1>✮ </color><white><task><gray>: <color:#FFAA00><progress></color>"

  # The lore when completed
  completed_lore:
    - "<st><color:#FFFC00><shadow:#000000:1>✮ </color><white><task><gray>: <color:#FFAA00><progress></color></st>"
    - "<!i><#55aaff><shadow:#000000:1>Press <key:key.use> <color:#AAAAAA>to advance</color>"

  # The requirement range.
  # Can be a single number "10", a range "10-20", "10+" (10 to MAX), or "-10" (0 to 10).
  requirement_range: -50

  # The default category. MUST exist in your config.yml 'categories' section.
  category: "easy"

  # Item settings
  item_rarity: "EPIC"    # COMMON, UNCOMMON, RARE, EPIC
  item_material: "PAPER" # Any valid Bukkit Material
  item_model: "" # The texture of the item, leave empty or remove if you don't wish to have a custom texture
  completed_item_model: "" # The texture of the item when completed, defaults to item_model if not set

  # blacklisted_worlds: # The list of blacklisted worlds for the mission, uncomment it if you want to set
  #   - "spawn_world"

  # Default mission options (conditions) that apply to missions using this default
  # custom_options:
  #   permission:
  #     values: [ "easymissions.default" ]

  # Default rewards.
  # Specific missions can inherit these by adding "[REWARDS!]" to their rewards list.
  rewards:
    - "say <gold><b>Congratulations!"

# You can define your own defaults, the plugin will come with some premade ones for each category as a demonstration.

default_easy:
  name: "<b><gradient:#0DFF00:#236A26><shadow:#000000:1>Easy Mission</shadow></gradient></b>"
  completed_name: "<green><bold>✔ COMPLETED</bold></green>"

  lore:
    - "<!i><shadow:#000000:1><white>Complete the mission to earn a</shadow>"
    - "<gradient:#0DFF00:#236A26><shadow:#000000:1>reward</gradient><white>."
    - ""
    - "<color:#0DFF00><shadow:#000000:1>✮ </color><white><task><gray>: <color:#0DFF00><progress></color>"

  completed_lore:
    - "<st><color:#0DFF00><shadow:#000000:1>✮ </color><white><task><gray>: <color:#0DFF00><progress></color></st>"
    - "<!i><#55aaff><shadow:#000000:1>Press <key:key.use> <color:#AAAAAA>to claim your rewards</color>"

  requirement_range: -50
  category: "easy"
  item_rarity: "COMMON"
  item_material: "PAPER"
  rewards:
    - "say <dark_green><b>Amazing!"


default_medium:
  name: "<b><gradient:#FFA500:#FFCC33><shadow:#000000:1>Medium Mission</shadow></gradient></b>"
  completed_name: "<green><bold>✔ COMPLETED</bold></green>"

  lore:
    - "<!i><shadow:#000000:1><white>Complete the mission to earn a</shadow>"
    - "<gradient:#FFA500:#FFCC33><shadow:#000000:1>reward</gradient><white>."
    - ""
    - "<color:#FFA500><shadow:#000000:1>✮ </color><white><task><gray>: <color:#FFA500><progress></color>"

  completed_lore:
    - "<st><color:#FFA500><shadow:#000000:1>✮ </color><white><task><gray>: <color:#FFA500><progress></color></st>"
    - "<!i><#55aaff><shadow:#000000:1>Press <key:key.use> <color:#AAAAAA>to claim your rewards</color>"

  requirement_range: 50-150
  category: "medium"
  item_rarity: "RARE"
  item_material: "PAPER"
  rewards:
    - "say <gold><b>Good job!"


default_hard:
  name: "<b><gradient:#FF0000:#611C1C><shadow:#000000:1>Hard Mission</shadow></gradient></b>"
  completed_name: "<green><bold>✔ COMPLETED</bold></green>"

  lore:
    - "<!i><shadow:#000000:1><white>Complete the mission to earn a</shadow>"
    - "<gradient:#FF0000:#611C1C><shadow:#000000:1>reward</gradient><white>."
    - ""
    - "<color:#FF0000><shadow:#000000:1>✮ </color><white><task><gray>: <color:#FF0000><progress></color>"

  completed_lore:
    - "<st><color:#FF0000><shadow:#000000:1>✮ </color><white><task><gray>: <color:#FF0000><progress></color></st>"
    - "<!i><#55aaff><shadow:#000000:1>Press <key:key.use> <color:#AAAAAA>to claim your rewards</color>"

  requirement_range: 150-300
  category: "hard"
  item_rarity: "EPIC"
  item_material: "PAPER"
  rewards:
    - "say <red><b>Great job."
